<#
.SYNOPSIS
    Copies my-fathers-work-template's shared style/layout/asset/setup/scoring content into a real
    module, matching the ownership split documented in this repo's CLAUDE.md.

.DESCRIPTION
    Template-canonical, mirror-copied (overwrite on collision, existing target-only files are never
    deleted): assets/audio/sfx/, assets/audio/bgm/ (Phase 5 Milestone 6.2 — the setup-passage theme
    and the shared 4-track ending-sequence playlist; a target module can still have its own
    additional module-specific bgm files alongside these, they're just never deleted or overwritten
    unless the filename collides), assets/fonts/, assets/icons/ (combines with the target's own —
    template wins only on a filename collision, the target's unique icons are left alone),
    assets/images/{backgrounds,borders,inputs,popup,progress}/, assets/style.css, and every
    layouts/*.mws.yaml. Never touches assets/audio/vo, images directly under assets/images/, or
    images/setup/ — those are the target module's own scenario-specific content.

    Also copies the template's _Setup_01..08/_Scoring_01..04 passages verbatim (same filenames) into
    the target's passages-override/, the variables/players.yaml and variables/scoring.yaml
    declarations backing them (under a template-owned filename, so an existing same-concern file in
    the target is never overwritten — see that copy step's own comment for why a module without
    those variables already declared will otherwise crash the first time it reads one), and merges
    every restext key the copied passages reference — plus Common_Close/Common_Continue — from the
    template's own en-US.restext into the target's en-US.overrides.restext (ModuleLoader's
    extraction-exempt merge-on-top file, not en-US.restext itself or .source/en-US.common.restext —
    both of those get regenerated by extraction and would silently lose these keys on the next
    re-run), add-only: an existing key (there or in the target's real extracted en-US.restext) is
    never overwritten, and a fresh re-run only ever adds what's still missing.

    -ProgressVariable handles a real integration gap this repo's own progress-bar layouts have: they
    read a 1-based `roundNum` (1-9), but a module extracted with --progress-map support instead sets
    an extractor-synthesized 0-based "rounds completed so far" variable (cost-of-disease's own is
    _ProgressRound — see progress-map.json's _comment). When given, this inserts one
    `let roundNum = min(<ProgressVariable> + 1, 9)` node as the first header entry of
    narration/introduction/hub_early/hub_middle/hub_late's freshly-copied layout files, right after
    every re-run's fresh copy from the template (so template-side edits to those layouts keep
    flowing through — this patch is reapplied on top each time, never hand-maintained separately).
    Omit if the target module will supply roundNum directly (or doesn't use the round-progress bar).

    This is the mechanical half of "harvest the template's design back into a real module" — a
    `git diff` + manual reconciliation inside the target module is still expected afterward:
    - Any tie-in passage the target hands off to from Setup_07 (target: '00_Preparations' in the
      template's own copy) needs to already exist in the target with a real chrome layout (not the
      retired 'setup_scenario') — this script never creates or touches it.
      END/ending passages (or whatever a target module's own "game complete" passages are named)
      need their own popup checked against the template's VarEndingsPassage pattern by hand — a
      real content decision (label text, popup layout name, restext correctness), not something
      this script can safely infer per module. See my-fathers-work-template/VIEW-REQUIREMENTS.md.
    - Run the target's own scratch test harness (or build one) end-to-end afterward — this script
      doesn't validate anything it writes.

.PARAMETER TargetModule
    Directory name of the module to copy into (e.g. 'cost-of-disease'), relative to this repo's root.

.PARAMETER TemplateModule
    Directory name of the source template module. Defaults to 'my-fathers-work-template'.

.PARAMETER ProgressVariable
    Session variable to derive roundNum from (e.g. '_ProgressRound'). Omit if not needed — see
    DESCRIPTION.

.EXAMPLE
    .\scripts\apply-template.ps1 -TargetModule cost-of-disease -ProgressVariable _ProgressRound -WhatIf
    Previews what would be copied/merged without touching anything.

.EXAMPLE
    .\scripts\apply-template.ps1 -TargetModule cost-of-disease -ProgressVariable _ProgressRound
    Applies for real — this is the exact invocation that reproduces cost-of-disease's own first
    manual merge. Follow up with `git diff` inside cost-of-disease/ before committing.
#>
[CmdletBinding(SupportsShouldProcess)]
param(
    [Parameter(Mandatory)]
    [string]$TargetModule,

    [string]$TemplateModule = 'my-fathers-work-template',

    [string]$ProgressVariable
)

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
$src = Join-Path $repoRoot $TemplateModule
$dst = Join-Path $repoRoot $TargetModule

if (-not (Test-Path (Join-Path $src 'manifest.yaml'))) {
    throw "Template module not found: $src"
}
if (-not (Test-Path (Join-Path $dst 'manifest.yaml'))) {
    throw "Target module not found: $dst"
}

function Copy-TrackedFile {
    param([string]$RelativeSourcePath, [string]$RelativeDestPath = $RelativeSourcePath)

    $from = Join-Path $src $RelativeSourcePath
    if (-not (Test-Path $from)) {
        Write-Warning "Skipping (not present in template): $RelativeSourcePath"
        return
    }

    $to = Join-Path $dst $RelativeDestPath
    if ($PSCmdlet.ShouldProcess($to, "Copy from $from")) {
        $toDir = Split-Path -Parent $to
        if (-not (Test-Path $toDir)) {
            New-Item -ItemType Directory -Path $toDir -Force | Out-Null
        }
        Copy-Item -LiteralPath $from -Destination $to -Force
        Write-Host "Copied $RelativeSourcePath -> $RelativeDestPath"
    }
}

function Copy-TrackedDirectory {
    param([string]$RelativeDir)

    $from = Join-Path $src $RelativeDir
    if (-not (Test-Path $from)) {
        Write-Warning "Skipping (not present in template): $RelativeDir"
        return
    }

    $to = Join-Path $dst $RelativeDir
    if ($PSCmdlet.ShouldProcess($to, "Mirror-copy directory from $from")) {
        New-Item -ItemType Directory -Path $to -Force | Out-Null
        Copy-Item -Path (Join-Path $from '*') -Destination $to -Recurse -Force
        Write-Host "Copied $RelativeDir/ -> $RelativeDir/"
    }
}

# ── Template-canonical assets ────────────────────────────────────────────────
$canonicalDirs = @(
    'assets/audio/sfx',
    'assets/audio/bgm',
    'assets/fonts',
    'assets/icons',
    'assets/images/backgrounds',
    'assets/images/borders',
    'assets/images/inputs',
    'assets/images/popup',
    'assets/images/progress',
    'layouts'
)
foreach ($dir in $canonicalDirs) {
    Copy-TrackedDirectory $dir
}
Copy-TrackedFile 'assets/style.css'

# ── roundNum derivation patch ─────────────────────────────────────────────────
# Runs after the fresh layouts/ copy above, so it's always reapplied on top of whatever the
# template's own copy of these files currently looks like — never hand-maintained separately.
if ($ProgressVariable) {
    $roundNumLayouts = @('narration', 'introduction', 'hub_early', 'hub_middle', 'hub_late')
    # The comment is baked into the patch itself (not left for a human to re-add after every
    # re-run, which is what earlier invocations of this script did) — it's regenerated fresh each
    # time alongside the code it explains, so it can never drift stale.
    $letBlock = @"
header:
# $TargetModule-specific: the template's own copy of this layout assumes a module already supplies
# roundNum (1-9) directly. This module's extractor-synthesized progress tracking (progress-map.json,
# --progress-map) instead sets $ProgressVariable, a 0-based "rounds completed so far" count (0 while
# playing round 1, ..., 8 while playing round 9, reaching 9 only once round 9's hub has been left) --
# so roundNum is derived here rather than being a real module variable. min(..., 9) clamps the
# ending/scoring narration (rendered after $ProgressVariable reaches 9) to a full bar instead of an
# out-of-range 10th case the switch below has no match for. Reproduced by
# scripts/apply-template.ps1 -ProgressVariable $ProgressVariable (see that script's own
# .DESCRIPTION) -- re-running it regenerates this exact block, so hand-edits here don't need to
# survive a re-run.
- type: 'let'
  var: 'roundNum'
  expr: 'min($ProgressVariable + 1, 9)'
"@
    foreach ($layout in $roundNumLayouts) {
        $path = Join-Path $dst "layouts/$layout.mws.yaml"
        if (-not (Test-Path $path)) {
            Write-Warning "Skipping roundNum patch (layout not present): $layout"
            continue
        }
        $text = Get-Content -LiteralPath $path -Raw
        if ($text -notmatch '(?m)^header:') {
            Write-Warning "Skipping roundNum patch (no 'header:' key found): $layout"
            continue
        }
        if ($PSCmdlet.ShouldProcess($path, "Insert roundNum <- $ProgressVariable derivation")) {
            # MatchEvaluator (not a replacement-pattern string) so $letBlock's own literal '$' text
            # (inside the 'expr' string) is never misread as a regex backreference.
            $evaluator = [System.Text.RegularExpressions.MatchEvaluator] { param($m) $letBlock }
            $patched = [regex]::new('(?m)^header:').Replace($text, $evaluator, 1)
            Set-Content -LiteralPath $path -Value $patched -NoNewline
            Write-Host "Patched layouts/$layout.mws.yaml (roundNum <- $ProgressVariable)"
        }
    }
}

# ── Setup + Scoring override passages ─────────────────────────────────────────
$overridePassages = @(
    '_Setup_01_PlayerCountSelect.mws.yaml',
    '_Setup_02_PlayerNameIntro.mws.yaml',
    '_Setup_03_PlayerNameA.mws.yaml',
    '_Setup_04_PlayerNameB.mws.yaml',
    '_Setup_05_PlayerNameC.mws.yaml',
    '_Setup_06_PlayerNameD.mws.yaml',
    '_Setup_07_TownNameEntry.mws.yaml',
    '_Setup_08_NarrationVoiceSelect.mws.yaml',
    '_Scoring_01_ScoreEntry.mws.yaml',
    '_Scoring_02_TieBreaker1.mws.yaml',
    '_Scoring_03_TieBreaker2.mws.yaml',
    '_Scoring_04_Ranking.mws.yaml'
)
foreach ($file in $overridePassages) {
    Copy-TrackedFile "passages/$file" "passages-override/$file"
}

# ── Variable declarations backing the copied override passages ───────────────
# players.yaml (nameA-D/players/playtxt/townname) and scoring.yaml (score_mwA-D/score_euA-D/
# winnerA-D/winnerCount) back the Setup/Scoring passages just copied above — without them, any
# session variable a target module hasn't already declared via extraction throws
# Masterwork.Engine.StoryEvalException ("Unknown variable") the first time a passage reads it (this
# is exactly the bug that motivated adding this section — cost-of-disease happened to already have
# every name covered via its own extraction + its own pre-existing variables/scoring.yaml, so it
# never hit this, but a module without that luck will). progress.yaml (roundNum) and game.yaml
# (ending) are template-showcase-only — every module-facing layout derives roundNum via a 'let' (see
# the roundNum patch above), never a persistent declaration, and ending-selection is each module's
# own responsibility, not something the showcase demonstrates — and showcase.yaml is demo-only
# bookkeeping, same as assets/images/_demo/ — so none of those three are copied.
#
# Copied under a template-owned filename, not e.g. "scoring.yaml", so a target module's own
# same-concern file is never overwritten (cost-of-disease's own variables/scoring.yaml predates this
# template and is more specific to that module) — MWS loads every variables/*.yaml regardless of
# name, and a harmlessly-redundant duplicate declaration of an already-covered variable is fine.
Copy-TrackedFile 'variables/players.yaml' 'variables/template-players.yaml'
Copy-TrackedFile 'variables/scoring.yaml' 'variables/template-scoring.yaml'

# ── Restext merge (add-only) ──────────────────────────────────────────────────
# Target: en-US.overrides.restext, not en-US.restext or .source/en-US.common.restext. Both of
# those get regenerated by extraction (ModuleLoader.ReadRestextWithOverride's own doc comment —
# see this repo's CLAUDE.md) — .source/en-US.common.restext specifically only gives *stable names
# to strings extraction already auto-detects as repeated*, it doesn't inject arbitrary keys that
# were never auto-detected in the first place, which these Setup_*/Scoring_* passage strings never
# are (they don't exist in the module's own Cradle source at all — they're template-authored, not
# extracted). An earlier version of this script wrote to both of those anyway, on the mistaken
# assumption that the common-restext merge would survive re-extraction; it silently didn't, and the
# next re-extraction wiped every key this section had ever added. en-US.overrides.restext is
# ModuleLoader's actual "never touched by extraction, merged on top with add/override-by-key
# semantics" mechanism — the one already built for exactly this.
function Get-RestextKeys {
    param([string]$Path)
    $keys = New-Object 'System.Collections.Generic.Dictionary[string,string]'
    if (-not (Test-Path $Path)) { return $keys }
    foreach ($line in Get-Content -LiteralPath $Path) {
        if ($line -match '^([A-Za-z0-9_]+)=(.*)$') {
            $keys[$Matches[1]] = $Matches[2]
        }
    }
    return $keys
}

$templateRestext = Get-RestextKeys (Join-Path $src 'en-US.restext')
$targetRestextKeys = Get-RestextKeys (Join-Path $dst 'en-US.restext')
$targetOverridesPath = Join-Path $dst 'en-US.overrides.restext'
$targetOverrideKeys = Get-RestextKeys $targetOverridesPath

$referencedKeys = New-Object 'System.Collections.Generic.HashSet[string]'
[void]$referencedKeys.Add('Common_Close')
[void]$referencedKeys.Add('Common_Continue')
foreach ($file in $overridePassages) {
    $copiedPath = Join-Path $dst "passages-override/$file"
    if (-not (Test-Path $copiedPath)) { continue }
    $text = Get-Content -LiteralPath $copiedPath -Raw
    foreach ($m in [regex]::Matches($text, 'restext://([A-Za-z0-9_]+)')) {
        [void]$referencedKeys.Add($m.Groups[1].Value)
    }
}

# Already resolvable via a real extracted key (the module's own Cradle source happens to cover it)
# doesn't need an override entry — only what's missing from *both* layers goes to overrides.
$missingKeys = $referencedKeys |
    Where-Object { -not $targetRestextKeys.ContainsKey($_) -and -not $targetOverrideKeys.ContainsKey($_) } |
    Sort-Object
if ($missingKeys.Count -gt 0) {
    $newLines = New-Object 'System.Collections.Generic.List[string]'
    foreach ($key in $missingKeys) {
        if ($templateRestext.ContainsKey($key)) {
            $newLines.Add("$key=$($templateRestext[$key])")
        }
        else {
            Write-Warning "Referenced restext key has no template value either, skipping: $key"
        }
    }

    if ($newLines.Count -gt 0) {
        if ($PSCmdlet.ShouldProcess($targetOverridesPath, "Add $($newLines.Count) restext keys")) {
            if (-not (Test-Path $targetOverridesPath)) {
                Set-Content -LiteralPath $targetOverridesPath -Value '# passages-override/_Setup_*.mws.yaml, _Scoring_*.mws.yaml — hand-authored, template-supplied'
                Add-Content -LiteralPath $targetOverridesPath -Value '# onboarding/scoring flow (masterwork.template). Regenerated by scripts/apply-template.ps1 --'
                Add-Content -LiteralPath $targetOverridesPath -Value "# add-only, so a hand-added key alongside these survives a re-run."
                Add-Content -LiteralPath $targetOverridesPath -Value ''
            }
            else {
                Add-Content -LiteralPath $targetOverridesPath -Value ''
            }
            Add-Content -LiteralPath $targetOverridesPath -Value $newLines
            Write-Host "Added $($newLines.Count) restext keys to en-US.overrides.restext"
        }
    }
}
else {
    Write-Host "No new restext keys needed — target already has everything the copied passages reference."
}

Write-Host "`nDone. Manual follow-ups this script deliberately doesn't do (see this script's own .DESCRIPTION):"
Write-Host "  - Confirm the target's own tie-in passage for Setup_07's handoff (target: '00_Preparations') exists and uses a real layout."
Write-Host "  - Check the target's own ending/game-complete passages against the template's VarEndingsPassage pattern by hand."
Write-Host "  - Review with 'git diff' inside $TargetModule/ and run the target's own test harness before committing."
